### PR TITLE
Add more mimetypes

### PR DESCRIPTION
**Pull request by roidelapluie**
Signed-off-by: Julien Pivotto <roidelapluie@o11y.eu>

### CODE REVIEW

**Comment by Nexucis** [comment]
to avoid the same situation, can you add more mimes. For example this list should cover all cases we have in React: 

https://github.com/perses/perses/blob/main/internal/api/front/generate.go#L31-L43

**Comment by Nexucis** [comment]
by checking on https://developer.mozilla.org/fr/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types, it looks like my MimeTypes are not accurate for JS and ICO but for the rest they are correct.

If you can update the list, we should be good for a while

**Comment by roidelapluie** [comment]
cjs
css
eot

ico
js
json
less
map
svg
ttf
txt
woff
woff2


is what we have. I have removed html from the list for now.

**Review by Nexucis — APPROVED** [review]
lgtm.

Just in case, the react-app has an `index.html`. SO HTML file exist. But I think anyway we are good like that. HTML files seems to be naturally supported somehow lol.

**Pull request merged**
