### PR TITLE
Update client_golang

### PR DESCRIPTION
**Pull request by sagikazarmark**
This update is necessary to finish the dependency graph cleanup in #255 (0.27.0 updated to a client_golang version that in turn used a common version that still relied on go-kit).

### CODE REVIEW

**Comment by roidelapluie** [comment]
Thanks!

**Comment by sagikazarmark** [comment]
@roidelapluie thanks for the quick merge. Any chance you could cut a release, so that dependent packages can use the latest of both common and client_golang?

**Comment by roidelapluie** [comment]
Sure, done. v0.28.0.

**Comment by sagikazarmark** [comment]
Awesome, thanks!

**Pull request merged**
