### PR TITLE
AddingPowerSupport_CI/Testing

### PR DESCRIPTION
**Pull request by santosh653**
Adding Power support & updating go versions to >=1.13 as lower versions are not supported.,

Adding power support ppc64le with Continues Integration/testing so that code remains architecture independent.

This is part of the Ubuntu distribution for ppc64le. This helps us simplify testing later when distributions are re-building and re-releasing. For more info tag @gerrith3.

The build is successful on both arch: amd64/ppc64le, please find the Travis Link below.
https://travis-ci.com/github/santosh653/common

Please let me know if you need any further details.

Thanks You !!

### CODE REVIEW

**Comment by brian-brazil** [comment]
This library support 1.9 or higher as client_golang does, so we shouldn't remove tests for those versions.

We're also looking to move off of Travis.

**Comment by santosh653** [comment]
@brian-brazil some of dependent packs are not available for go 1.9/1.10 hence excluding them and running the code for rest all other go versions.,
Hope this change answers/addresses your query.
The build is successful for rest all.

Thanks you !!

**Comment by brian-brazil** [comment]
We're looking to move off Travis and delete this file, so if you're going to propose any changes it should be over in the CircleCI config.

**Comment by gerrith3** [comment]
@brian-brazil Circle CI does not currently have any ppc64le hardware or access to it at the moment. We are looking into adding them to our CI set but it may be a while.

**Comment by brian-brazil** [comment]
I'm afraid there's not much to do then, as we're moving off Travis.

**Comment by santosh653** [comment]
Are there any queries open on this PR?

**Comment by gerrith3** [comment]
@brian-brazil have you considered running travis for ppc64le/s390x/arm/etc. and CircleCI for intel?  The reason I ask is that prometheus is pretty heavily used on ppc64le and we wind up having to do side ports and validation fairly often.   It would be nice if the top of tree were tested on ppc64le and probably s390x as well.

**Comment by brian-brazil** [comment]
To be clear, we are planning on completely getting rid of Travis. If you care about Prometheus then the place to test would be over in the Prometheus repo - any endian stuff is over there.

**Comment by santosh653** [comment]
Do we have any further queries on this PR? & Is this PR getting merged?

**Comment by brian-brazil** [comment]
This PR will not be merged, as I said we're getting rid of Travis and thus there's not much point in making changes to something we're about to delete.

**Comment by SuperQ** [comment]
We don't use Travis CI anymore.

**Pull request closed without merging**
