### PR TITLE
Change default validation scheme to UTF8Validation

### PR DESCRIPTION
**Pull request by ywwg**
fixes https://github.com/prometheus/common/issues/723

### CODE REVIEW

**Comment by SuperQ** [comment]
Is there any coordination with client_golang we need here? This seems like it may be a transparent breaking change for some systems.

**Comment by ywwg** [comment]
I'll test it out -- probably yes we want to coordinate releases

**Review by bwplotka — APPROVED** [review]
Thanks!

Yea let's update client_golang straight away with this and explicitly set this if needed.

**Comment by bwplotka** [comment]
Ok, this breaks in quite many places (client_golang, prometheus, outside users like Google), changing global and defer to change back does not scale really. We might consider fixing 0.62.0 and change all those functions to actually NOT use global cc @ywwg @SuperQ

**Comment by bwplotka** [comment]
The challenge is UnmarshalJSON and so, plus doing this in backward compatible way. Unless we want to add more validation scheme OR the cases where legacy has to be used, it might be indeed easier to break everyone here ):

**Comment by bwplotka** [comment]
Added big warning to release https://github.com/prometheus/common/releases/tag/v0.62.0

**Pull request merged**
