### PR TITLE
config: add SetDirectory methods

### PR DESCRIPTION
**Pull request by abursavich**
Part of cleanup for https://github.com/prometheus/prometheus/pull/7701

### CODE REVIEW

**Comment by brian-brazil** [comment]
Why does this need to change?

This also doesn't look right, as it's mutating the config the user passed in.

**Comment by abursavich** [comment]
It's a step in parsing a config file to allow for relative paths.

**Comment by brian-brazil** [comment]
Parsing should not involve changing the config file, as we need to render it back to the user. The code already does relative paths.

**Comment by abursavich** [comment]
Maybe I should've said it's a step in "loading" a config file.

https://github.com/prometheus/prometheus/blob/f482c7bdd734ba012f6cedd68ddc24b1416efb35/config/config.go#L55-L67
https://github.com/prometheus/prometheus/blob/f482c7bdd734ba012f6cedd68ddc24b1416efb35/config/config.go#L145-L215

I think it would be cleaner to have the code in this package, but it can live elsewhere and be more clunky:

`func SetBasicAuthDirectory(c *config.BasicAuth, dir string)`
`func SetTLSConfigDirectory(c *config.TLSConfig, dir string)`
`func SetHTTPClientConfigDirectory(c *config.HTTPClientConfig, dir string)`

**Pull request closed without merging**
