### PR TITLE
Backport json 0.0.2 format

### PR DESCRIPTION
**Pull request by fabxc**
@beorn7 @juliusv

### CODE REVIEW

**Comment by juliusv** [comment]
Curious: Is this "because we can" or was there a new need for this that I'm not aware of yet?

**Comment by fabxc** [comment]
To many *-kits out there, applications with possibly pinned versions of such kits. In total, dragging this with us probably saves us some trouble.

**Comment by juliusv** [comment]
Hmm, is there a reason to assume that any of these kits ever used the JSON format, given that we've never documented it, and at the time of going public, we didn't have any client library anymore which would default to that format?

**Comment by juliusv** [comment]
s/default to that format/not support protobuf when asked/

**Comment by juliusv** [comment]
(or text)

**Comment by fabxc** [comment]
I'm not referring to public kits :)

**Comment by juliusv** [comment]
:+1: after chatting. Ok, let's put this back temporarily, but make a plan for phasing out the remaining JSON endpoints and then getting rid of this forever again...

**Pull request merged**
