### PR TITLE
Add functions to reduce use of globals.

### PR DESCRIPTION
**Pull request by Gouthamve**
These functions will be used to construct and pass around the logger in prometheus.

@grobie @fabxc @brian-brazil

---
This change is [Reviewable](https://reviewable.io/reviews/prometheus/common/87)

### CODE REVIEW

**Comment by grobie** [comment]
LGTM but I'm concerned about the amount of code we write without tests.

**Comment by fabxc** [comment]
@grobie that's more of a package structure than a semantic change. The larger added code block is a straight copy of https://github.com/prometheus/common/blob/master/log/log.go#L67-L107 AFAICS.

@Gouthamve maybe we could deduplicate that?

**Comment by Gouthamve** [comment]
Done. No clue why I did not do that before, sorry.

**Comment by fabxc** [comment]
:+1:

**Comment by grobie** [comment]
@fabxc I'm aware that it was mostly copied code. I don't see how that justifies not having tests?

**Comment by fabxc** [comment]
It's a logging library wrapper. I know 90%+ test coverage would be fantastic. As it always has been, we do not have remotely the resources to invest that kind of effort.
We have a 2.0 release to get out. Thew new TSDB is significantly better tested than this package here. I hope that's somewhat reassuring :)

**Comment by grobie** [comment]
It is!

**Pull request merged**
