### PR TITLE
Update Go modules

### PR DESCRIPTION
**Pull request by SuperQ**
* Replace deprecated `github.com/golang/protobuf` dependency.
* Update various Go modules.

### CODE REVIEW

**Comment by beorn7** [comment]
Nothing works… :-/

**Comment by SuperQ** [comment]
Not sure what to do about this issue:
```
  Error: copylocks: assignment copies lock value to *v: github.com/prometheus/client_model/go.MetricFamily contains google.golang.org/protobuf/internal/impl.MessageState contains sync.Mutex (govet)
  ```

**Comment by beorn7** [comment]
Now that we can see the required changes here:

Isn't that exactly the problem that has kept us from doing this kind of upgrade? This will trickle down to prometheus/client_golang, and then users of client_golang that have been importing `github.com/golang/protobuf/proto` have to change their imports to `google.golang.org/protobuf/proto`, but the need for that isn't signaled by a major version bump of client_golang.

Not everyone is actually touching any proto types when using client_golang, but there will still be a lot of users affected. @bwplotka @kakkoyun WDYT?

**Comment by SuperQ** [comment]
I don't think it's actually an issue, we just need to do the update and the circular dependency will resolve. This moves the old library to an indirect dependency, which means it will vanish from client_golang in the next release.

**Comment by beorn7** [comment]
I think I'm referring to something else.

Look at https://github.com/beorn7/histogram_experiments/blob/master/cmd/float_gauge/main.go as a somewhat weird example (but there are less invasive usages out there that will run into the same problem). It is manipulating the metrics during gathering on the level of the proto types. This program will need to be changed (at least the import line, possibly more) with the first release of client_golang that includes these updates. That's technically a breaking change that is not signaled by a major version bump.

**Comment by beorn7** [comment]
I mean, we can blame Google for having screwed up the Go implementation of protobuf, and go with it. But it's not an easy call. Therefore ping'ing @bwplotka and @kakkoyun .

**Comment by beorn7** [comment]
About the copylocks warning: That's to be taken seriously, I think. It's in expfmt/decode.go:135 . Maybe we can explicitly copy just the exported fields? I'll try to propose something.

**Comment by beorn7** [comment]
> Ok, so the breaking change is that github.com/golang/protobuf/proto usages have to change their imports to google.golang.org/protobuf/proto when client_golang will be upgraded.

Yes, but maybe also change code, in the same style as in this PR.
This only affects users who are directly touching types from the proto package, which is not common, but not super uncommon, either.

**Comment by SuperQ** [comment]
Most users of client_golang don't directly manipulate the proto. So for most users it's just going to be a Go modules change and will happen automatically.

**Comment by beorn7** [comment]
I have added a commit that should fix the lint warning.

**Comment by SuperQ** [comment]
I did a quick search, the only prometheus code I could find that directly manipulates the proto is the pushgateway.

**Comment by beorn7** [comment]
Yeah, that's a good data point.

**Review by beorn7 — APPROVED** [review]
Approving, but the final call should be made by @bwplotka & @kakkoyun.

**Review by bwplotka — APPROVED** [review]
Thanks!

**Pull request merged**
