### PR TITLE
update to github.com/sirupsen/logrus v1.0.0

### PR DESCRIPTION
**Pull request by mcandre**
Signed-off-by: Andrew Pennebaker <apennebaker@datapipe.com>

Fix some dependencies by updating to github.com/sirupsen/logrus v1.0.0 (the original project has moved away from github.com/Sirupsen/logrus).

### CODE REVIEW

**Comment by fabxc** [comment]
Thanks! :+1:

**Comment by grobie** [comment]
Huh. This is a Noop merge, see https://github.com/prometheus/common/commit/3e6a7635bac6573d43f49f97b47eb9bda195dba8.

The sirupsen log change was already done 3 weeks ago.

**Comment by fabxc** [comment]
Why's the diff showing something then?

**Comment by grobie** [comment]
The parent commit of @mcandre's commit is ancient from Nov 14, 2016, that's what the diff is showing.

**Comment by fabxc** [comment]
Alright, but no damage done I suppose :)

**Pull request merged**
