### PR TITLE
Add JSON markshal and unmarshal support for model.Duration

### PR DESCRIPTION
**Pull request by sid-agrawal**
@brian-brazil this PR addresses https://github.com/prometheus/common/issues/227

Signed-off-by: Sid Agrawal <sid@arista.com>

### CODE REVIEW

**Comment by sid-agrawal** [comment]
After applying this diff I was able to successfully Unmarshal github.com/prometheus/alertmanager/config.Config

**Comment by roidelapluie** [comment]
The prometheus project is not using json anywhere, why do you need this?

**Comment by roidelapluie** [comment]
Thanks for your contribution.

The prometheus project is not using json anywhere, why do you need this?

**Comment by brian-brazil** [comment]
This is an internal library of Prometheus, you shouldn't be depending on it.

**Comment by sid-agrawal** [comment]
> This is an internal library of Prometheus, you shouldn't be depending on it.
In that case I will close this PR.



> Thanks for your contribution.
> 
> The prometheus project is not using json anywhere, why do you need this?
I was looking for a Go Struct to save the config: https://prometheus.io/docs/alerting/configuration/.

This was my app could programmatically manipulate (i.e. add/delete) receivers, routes etc.

**Pull request closed without merging**
