### PR TITLE
Enable dependabot

### PR DESCRIPTION
**Pull request by SuperQ**
Add dependabot for monthly updates.

### CODE REVIEW

**Comment by roidelapluie** [comment]
all broken?

**Comment by mmorel-35** [comment]
Duplicates #436

**Comment by bboreham** [comment]
In my view, dependabot should be used in programs and not in libraries.

Updating dependencies of this library does nothing to update programs that use it, until they need a new feature from this library, and then they are forced to update whatever this library says.  Libraries should not be in the business of forcing updates.

**Comment by lucacome** [comment]
well this one and #436 are actually a duplicate of #433

**Comment by SuperQ** [comment]
Closing in favor of #433

**Pull request closed without merging**
