### PR TITLE
ci(deps): setup dependabot 

### PR DESCRIPTION
**Pull request by mmorel-35**
Signed-off-by: Matthieu MOREL <matthieu.morel35@gmail.com>

### CODE REVIEW

**Comment by bboreham** [comment]
In my view, dependabot should be used in programs and not in libraries.

Updating dependencies of this library does nothing to update programs that use it, until they need a new feature from this library, and then they are forced to update whatever this library says.  Libraries should not be in the business of forcing updates.

**Comment by lucacome** [comment]
This doesn't close #433 but some parts of this are a duplicate of it

**Comment by mmorel-35** [comment]
Hi @lucacome ,
It's now aligned 🙂!

**Comment by SuperQ** [comment]
Closing in favor of #433

**Pull request closed without merging**
