### PR TITLE
update dependencies of prometheus/common

### PR DESCRIPTION
**Pull request by tariq1890**

### CODE REVIEW

**Comment by brian-brazil** [comment]
Thanks!

**Comment by axw** [comment]
Was the inclusion of `vendor` intentional? This has broken prometheus/client_golang for non-module-aware versions of Go.

**Comment by beorn7** [comment]
I'm pretty sure we should not include the `vendor` directory in libraries.

See https://github.com/prometheus/client_golang/issues/625 for how this breaks users.

**Comment by brian-brazil** [comment]
#199 is out to fix

**Comment by tariq1890** [comment]
Whoops. Completely missed the vendor add. Why don't we include the gitignore for this though?

**Pull request merged**
