### PR TITLE
Update Go versions

### PR DESCRIPTION
**Pull request by SuperQ**
* Add Go 1.20.
* Set minimum Go version to 1.18.
* Bump golang.org/x/net.

### CODE REVIEW

**Comment by roidelapluie** [comment]
client_golang depends on ; have they / will they also bump the go version requirement?

**Comment by SuperQ** [comment]
Added client_golang maintainers to this.

**Comment by beorn7** [comment]
IIRC we are usually trying to support the last three Go minor releases. From that perspective, Go1.19 would be fine once Go1.21 is out. But I might misremember, and I'm pretty sure it was always a best-effort thing. (Although it's usually easy with build tags etc. to maintain backwards compatibility even if using more recent Go features.)

**Comment by SuperQ** [comment]
@beorn7 We used to do that, but recently we have been only trying to support only what Go officially supports.

**Comment by beorn7** [comment]
I guess @bwplotka and @kakkoyun should confirm or deny…

**Comment by SuperQ** [comment]
Ok, I added Go 1.18 back in.

I still want to get sign-off from both client_golang and prometheus maintainers.

**Comment by kakkoyun** [comment]
I won't have access to a computer until Sunday. If it's urgent, leaving the decision to @bwplotka

**Comment by bwplotka** [comment]
LGTM, thanks for keeping 1.18 in, not big harm here to keep it IMO.

**Review by bwplotka — APPROVED** [review]

**Comment by roidelapluie** [comment]
Thanks!

**Review by kakkoyun — COMMENTED** [review]
LGTM

**Pull request merged**
