### PR TITLE
Add http_config option for unprefixed (api) token authentication.

### PR DESCRIPTION
**Pull request by 0xDiddi**
As of now, the`http_config` only accepts OAuth bearer tokens and basic user+password authentication.

With these changes, you can specify an `api_token` or an `api_token_file` that will be used as the authentication header without any further prefixes, suffixes or other modifications.

This PR should (unless I've missed something) contain all required bits and pieces, including validation and unit tests.

cc @fabxc
as per #147 also cc @beorn7

### CODE REVIEW

**Comment by brian-brazil** [comment]
Thanks for your PR. I'm not sure we should support arbitrary non-standard authentication mechanisms, as that's getting a bit too niche.

**Comment by hphde** [comment]
What's really required is something that satisfies https://tools.ietf.org/html/rfc2616#page-107
Some part that sends out `Authorization: xyz` where as `xyz` can be anything like `String` or `Identifier String` or whatever you can think of.

**Comment by hphde** [comment]
@brian-brazil what do you say about rfc2616?

**Comment by brian-brazil** [comment]
I say that we comply with rfc2616, that doesn't mean we have to support every possible implementation variation of it though.

**Comment by hphde** [comment]
That's true, current Bearertoken implementation is compliant with the RFC but the PR satisfies it to a much broader extend. I don't know if it's an implementation of all variations - that would be awesome, since it's quite a small change.

**Comment by brian-brazil** [comment]
I'm going to close this off, as we still only support standard bearer tokens. We explicitly aren't trying to support every bespoke auth system that has been created, and you can always use a http proxy if you need something niche.

**Pull request closed without merging**
