### PR TITLE
model: Remove json-iterator usage (again)

### PR DESCRIPTION
**Pull request by beorn7**
This seemingly undoes #440, but all the json-iterator usage was actually pulled up into client_golang in
https://github.com/prometheus/client_golang/pull/1225 . Detailed explanation there. In short, we would like to keep heavy dependencies like json-iterator out of prometheus/common/model since many importers of this package aren't even interested in the JSON marshaling.

### CODE REVIEW

**Comment by beorn7** [comment]
@zenador as discussed. I believe, together with https://github.com/prometheus/client_golang/pull/1225 , this should still work out in Mimir. To try it out, just make sure you have vendored in both PRs.

**Review by roidelapluie — APPROVED** [review]

**Comment by SuperQ** [comment]
This needs a rebase to update the go.sum.

**Comment by beorn7** [comment]
OK, rebased. I will only merge this once https://github.com/prometheus/client_golang/pull/1225 is approved.

**Comment by beorn7** [comment]
With https://github.com/prometheus/client_golang/pull/1225 approved, I'll execute the following steps now:
- Merge this PR (#453).
- Tag a new minor version in this repo (common).
- Update to that new minor version over in client_golang in https://github.com/prometheus/client_golang/pull/1225 .
- Merge https://github.com/prometheus/client_golang/pull/1225

**Pull request merged**
