### PR TITLE
Convert exposition format to proto3.

### PR DESCRIPTION
**Pull request by juliusv**

### CODE REVIEW

**Comment by juliusv** [comment]
The CI fails because this depends on https://github.com/prometheus/client_golang/pull/233, which in turn depends on this change here. The two repos import each other circularly :-/

**Comment by fabxc** [comment]
👍

**Comment by juliusv** [comment]
We'll probably have to revert this, given the discussion in https://github.com/prometheus/client_model/issues/13 - giving it a day more to settle, but doesn't look good right now.

**Comment by grobie** [comment]
Please don't wait another day. This is regardless of the outcome of the discussion, at the moment all `go get`s of Prometheus projects are broken.

**Comment by juliusv** [comment]
Push a revert directly to master: https://github.com/prometheus/common/commit/616e90af75cc300730196d04f3676f838d70414f

**Pull request merged**
