### PR TITLE
Extend version.Print with platform info

### PR DESCRIPTION
**Pull request by dstdfx**
For https://github.com/prometheus/prometheus/issues/7962

### CODE REVIEW

**Comment by brian-brazil** [comment]
From context, I think @roidelapluie wants this in the logs so we can easily see it when users post issues. Having it only show on an extra command run doesn't really help.

**Comment by dstdfx** [comment]
> From context, I think @roidelapluie wants this in the logs so we can easily see it when users post issues. Having it only show on an extra command run doesn't really help.

In the referenced issue the output looks exactly like from ```prometheus --version``` command. Moreover the output of this command is mentioned in the [issue template](https://github.com/prometheus/prometheus/blob/master/.github/ISSUE_TEMPLATE/bug_report.md).

**Comment by roidelapluie** [comment]
Yes it is in prometheus --version as that is what we ask users to provide

**Review by roidelapluie — APPROVED** [review]

**Comment by roidelapluie** [comment]
We often only get the tail of the logs for users.

**Comment by brian-brazil** [comment]
Thanks!

**Pull request merged**
