### PR TITLE
Add source_address to HTTPClientConfig

### PR DESCRIPTION
**Pull request by bobrik**
This unlocks setting `source_ip_address` for HTTP probes in `blackbox_exporter`.

### CODE REVIEW

**Comment by bobrik** [comment]
https://github.com/prometheus/blackbox_exporter/pull/765 is how it's supposed to be used.

Not sure what to do with go1.9 and go1.10 failures.

**Comment by roidelapluie** [comment]
Can you rebase this ?

**Comment by bobrik** [comment]
Done, the conflict was in imports:

```
$ git diff config/http_config.go
diff --cc config/http_config.go
index 07de306,c0c4d5b..0000000
--- a/config/http_config.go
+++ b/config/http_config.go
@@@ -17,7 -17,8 +17,8 @@@ package confi

  import (
        "bytes"
+       "context"
 -      "crypto/md5"
 +      "crypto/sha256"
        "crypto/tls"
        "crypto/x509"
        "fmt"
```

**Comment by roidelapluie** [comment]
I think that it is not necessary to change common, that we could do everything in blackbox exporter.

**Comment by bobrik** [comment]
Here's what I came up with without changing `prometheus/common`: https://github.com/prometheus/blackbox_exporter/pull/766. It leaks some details about use of tracing and how dialer is set up otherwise in `prometheus/common`.

**Comment by SuperQ** [comment]
This needs a rebase.

**Pull request closed without merging**
