### PR TITLE
Bump github.com/sirupsen/logrus

### PR DESCRIPTION
**Pull request by simonpasquier**
See https://github.com/prometheus/consul_exporter/pull/120#issuecomment-506650462

### CODE REVIEW

**Comment by brian-brazil** [comment]
Shouldn't we be moving stuff to go kit?

**Comment by simonpasquier** [comment]
I agree. I can create the corresponding issues in the repositories that still use logrus.

@SuperQ WDYT?

**Comment by SuperQ** [comment]
Are we moving all logging from logrus to go kit? I'm not really a fan of it. While it's nice that it does structured logs, it made some stuff more difficult. @juliusv and I ran into some issues.

**Comment by brian-brazil** [comment]
That move was decided some time ago.

**Comment by juliusv** [comment]
Yeah, I didn't know we still had logrus around :)

**Comment by tariq1890** [comment]
I think this PR can be closed. Didn't know of this earlier, my bad.

**Pull request closed without merging**
